# Generated by Django 3.0.9 on 2023-07-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('product', 'order')},
        ),
    ]
