# Generated by Django 4.2.8 on 2024-09-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'unique_together': {('order_number', 'product_number')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='api.OrderProduct', to='api.product'),
        ),
    ]
