# Generated by Django 4.2.8 on 2025-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'type_a'), (2, 'type_b'), (3, 'type_c')])),
                ('material', models.IntegerField(choices=[(1, 'metal'), (2, 'cloth'), (3, 'wood')])),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
