# Generated by Django 3.0.9 on 2022-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220306_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='api.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.FloatField(),
        ),
    ]
