# Generated by Django 4.2.8 on 2024-10-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
    ]
