# Generated by Django 4.2.8 on 2025-05-12 18:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, validators=[api.models.validate_price], verbose_name='總金額'),
        ),
    ]
