# Generated by Django 4.2.8 on 2025-03-17 06:09

import api.dto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_order_customer_name_order_status_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELLED')], default=api.dto.Status['PENDING'], max_length=20),
        ),
    ]
