# Generated by Django 4.2.8 on 2025-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_buyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(default=0, unique=True, verbose_name='訂單編號'),
        ),
        migrations.AlterUniqueTogether(
            name='productsell',
            unique_together={('product', 'order')},
        ),
        migrations.AddConstraint(
            model_name='productsell',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_order'),
        ),
    ]
