# Generated by Django 4.2.8 on 2025-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8, unique=True)),
                ('sequence', models.IntegerField(default=1)),
            ],
        ),
    ]
