# Generated by Django 4.2.8 on 2025-05-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_order_num_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productsell',
            name='unique_product_order',
        ),
        migrations.AlterUniqueTogether(
            name='productsell',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pathway',
        ),
        migrations.AlterField(
            model_name='productsell',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productSell', to='api.product'),
        ),
        migrations.DeleteModel(
            name='Pathway',
        ),
    ]
