# Generated by Django 5.1.7 on 2025-03-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_payment_status_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='status',
        ),
    ]
