# Generated by Django 4.2.8 on 2025-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordernumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
