# Generated by Django 4.2.8 on 2025-03-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_updated_time_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
