# Generated by Django 4.2.8 on 2025-05-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productsell_unique_product_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsell',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSell', to='api.product'),
        ),
    ]
