# Generated by Django 4.2.8 on 2025-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderproduct_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
