# Generated by Django 4.2.8 on 2025-05-13 13:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_remove_order_total_price_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, validators=[api.models.validate_price], verbose_name='總金額'),
        ),
    ]
