# Generated by Django 5.1.7 on 2025-03-22 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0005_alter_order_total_price_and_more'), ('api', '0006_alter_product_price'), ('api', '0007_alter_order_total_price_and_more')]

    dependencies = [
        ('api', '0003_order_payment_status_alter_orderitem_order_squashed_0004_rename_payment_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
