# Generated by Django 4.2.8 on 2025-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productsell_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default='test123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='productsell',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_order'),
        ),
    ]
