# Generated by Django 5.1.7 on 2025-03-20 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
